# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A nice title
subtitle: "And a subtitle"
email: someusername@someprovider.com
description: "A nice description"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"
logo: "/images/weblogo.jpg"

#disqus: "Your disqus id"
#facebook: "Your Facebook Username"
#fb_app_id "Your Facebook App ID"

excerpt_separator: <!--more-->

# Build settings
markdown:           kramdown
highlighter:        rouge
kramdown:
  hard_wrap: true
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false

author:
  name: "Your Name"
  image: /images/weblogo.png
  bio: "A nice Bio"
  website: "Your website Link"
    
theme: minima
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]